### ISSUE TITLE
Namespaces and inheritance

### ISSUE THREAD

**Issue by nise** [dfilatov/jquery-plugins#5]
I am using your inheritance class for a couple of years but now I need to simulate namespaces in order to distinguish my classes from other libraries. Is there a approach to faciltate this with your inheritance plugin?

I tried the following without success.
var Namespace = {};
Namespace.ClassA = $.inherit( /\* ... */);

**Comment by dfilatov** [comment]
What exactly doesn't work? I can't see any reason why it can't work.

**Comment by nise** [comment]
Sorry, I made a mistake. var a = new Namespace.ClassA() works fine.
